name: Deploy Hugo site to Pages

on:
  push:
    branches: [ "main" ] # Trigger on push to main branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive # Fetch Hugo themes (if used as submodules)
          fetch-depth: 0 # Fetch all history for .GitInfo and lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Build with Hugo
        run: hugo --minify

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }} # <- Uses the automatic token
          publish_dir: ./public
          external_repository: KrisK7/krisk7.github.io
          publish_branch: main # The branch your Pages site is built from
